import { Service } from "../types";

export const SERVICES: Service[] = [
  {
    id: "1",
    name: "Cloud Infrastructure",
    description: "Scalable cloud solutions architected for your business workloads.",
    category: "Cloud",
    icon: "cloud",
    features: ["Cloud Migration", "Auto-scaling", "99.9% SLA", "24/7 Monitoring"],
    pricing: "From $299/mo",
    popular: true,
  },
  {
    id: "2",
    name: "Cybersecurity",
    description: "Multi-layered security to protect your data and infrastructure.",
    category: "Security",
    icon: "shield-checkmark",
    features: ["Threat Detection", "Firewall Management", "Security Audits", "Incident Response"],
    pricing: "From $199/mo",
    popular: true,
  },
  {
    id: "3",
    name: "Network Management",
    description: "Reliable, high-performance network design and management.",
    category: "Network",
    icon: "git-network",
    features: ["Network Design", "VPN Setup", "Bandwidth Optimization", "Remote Access"],
    pricing: "From $149/mo",
  },
  {
    id: "4",
    name: "IT Helpdesk Support",
    description: "Round-the-clock technical support for every employee.",
    category: "Support",
    icon: "headset",
    features: ["24/7 Support", "Remote Assistance", "On-site Visits", "Ticket System"],
    pricing: "From $99/mo",
    popular: true,
  },
  {
    id: "5",
    name: "Data Management",
    description: "Secure backup, disaster recovery, and compliance solutions.",
    category: "Data",
    icon: "server",
    features: ["Automated Backups", "Disaster Recovery", "Data Migration", "GDPR Compliance"],
    pricing: "From $179/mo",
  },
  {
    id: "6",
    name: "Software Solutions",
    description: "Custom software development and enterprise integration.",
    category: "Software",
    icon: "code-slash",
    features: ["Custom Development", "System Integration", "API Development", "Mobile Apps"],
    pricing: "Custom pricing",
  },
  {
    id: "7",
    name: "IT Consulting",
    description: "Strategic guidance to align technology with business goals.",
    category: "Consulting",
    icon: "analytics",
    features: ["IT Strategy", "Technology Assessment", "ROI Analysis", "Roadmap Planning"],
    pricing: "From $250/hr",
  },
  {
    id: "8",
    name: "Managed IT Services",
    description: "Complete end-to-end IT management for worry-free operations.",
    category: "Managed",
    icon: "settings",
    features: ["Proactive Monitoring", "Patch Management", "Asset Tracking", "Monthly Reports"],
    pricing: "From $499/mo",
    popular: true,
  },
];

export const SERVICE_CATEGORIES = [
  "All",
  "Cloud",
  "Security",
  "Network",
  "Support",
  "Data",
  "Software",
  "Consulting",
  "Managed",
];
